# Generated by Django 3.1.7 on 2022-04-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_load', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageinfo',
            old_name='correctnes',
            new_name='correctness',
        ),
    ]
