# Generated by Django 3.1.7 on 2022-10-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_load', '0002_auto_20220412_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageinfo',
            old_name='correctness',
            new_name='isAnime',
        ),
    ]
